### PR TITLE
update_features and json_props_to_pg_cols functions

### PR DESCRIPTION
**Pull request by strk**
Implementing #16

### CODE REVIEW

**Comment by strk** [comment]
@larsop the geometry CRS in the test JSON is EPSG:25833 but the `topo_ar5_sysdata_webclient` topology is built using SRID=4258, shall the geometry from JSON be transformed by this function ?

**Comment by larsop** [comment]
> @larsop the geometry CRS in the test JSON is EPSG:25833 but the `topo_ar5_sysdata_webclient` topology is built using SRID=4258, shall the geometry from JSON be transformed by this function ?

No , sorry here is correct JSON.

```
{"type":"Feature","geometry":{"type":"LineString","coordinates":[[65.16192253885816,12.140220106969867],[65.1619363265414,12.140232072734605],[65.16194457439238,12.140245489762707],[65.16195159942106,12.140274839374376],[65.16195644502434,12.1403076267815],[65.16195800836354,12.140323686083182],[65.16196000490535,12.140390730902928],[65.16195535592834,12.140415360200816],[65.16194796164967,12.140437296061128],[65.16192083623508,12.140455807015112],[65.1619000462266,12.140448652835481],[65.16188367648795,12.140428424352995],[65.16187664742714,12.140398861689315],[65.16187040506439,12.140358751608547],[65.16186989011845,12.140312899631391],[65.16187322736496,12.140290119972393],[65.16188096431031,12.140257898077769],[65.16190433092325,12.140221215579803],[65.16192253885816,12.140220106969867]]},"properties":{"featuretype":"ArealressursGrense","datafangstdato":"1965-07-22","verifiseringsdato":"1965-07-22","avgrensingType":"3000","opphav":"FKB-Vann","kvalitet":{"målemetode":"53","nøyaktighet":200,"synbarhet":"0"},"registreringsversjon":{"produkt":"FKB-AR5","versjon":"4.5 20140301"},"identifikasjon":{"navnerom":"AR5_test23","lokalId":"092688bb-c6ef-43c9-b6f7-41b2f065537c","versjonId":"2019-11-11 11:57:47.371000"},"oppdateringsdato":"2019-11-12T14:02:26"}}
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[65.16192253885816,12.140220106969867],[65.16190433092325,12.140221215579803],[65.16188096431031,12.140257898077769],[65.16187322736496,12.140290119972393],[65.16186989011845,12.140312899631391],[65.16187040506439,12.140358751608547],[65.16187664742714,12.140398861689315],[65.16188367648795,12.140428424352995],[65.1619000462266,12.140448652835481],[65.16192083623508,12.140455807015112],[65.16194796164967,12.140437296061128],[65.16195535592834,12.140415360200816],[65.16196000490535,12.140390730902928],[65.16195800836354,12.140323686083182],[65.16195644502434,12.1403076267815],[65.16195159942106,12.140274839374376],[65.16194457439238,12.140245489762707],[65.1619363265414,12.140232072734605],[65.16192253885816,12.140220106969867]]]},"properties":{"featuretype":"ArealressursFlate","arealtype":"81","treslag":"98","skogbonitet":"98","grunnforhold":"98","kartstandard":"AR5","datafangstdato":"1965-07-22","verifiseringsdato":"1965-07-22","opphav":"FKB-Vann","kvalitet":{"målemetode":"82","nøyaktighet":1,"synbarhet":"0"},"registreringsversjon":{"produkt":"FKB-AR5","versjon":"4.5 20140301"},"identifikasjon":{"navnerom":"AR5_test23","lokalId":"0008e6eb-1332-4145-9943-591020916480","versjonId":"2019-11-11 11:57:47.371000"},"oppdateringsdato":"2019-11-12T14:02:26"},"geometry_properties":{"position":[1.0949830530113682E-4,10.51183990117714],"exterior":["-092688bb-c6ef-43c9-b6f7-41b2f065537c"]}}
```

**Comment by strk** [comment]
> No , sorry here is correct JSON.

For now I've added support for reprojecting,
if you think wrong SRID should trigger an ERROR let me know and I'll
change to ERROR out in that case.

**Comment by strk** [comment]
So, in it's current status the `update_features` function is doing INSERTS for features with no matching UUID and UPDATE for those with a matching on. No attempt is made, at the moment, to determine whether or not an UPDATE is required. Rather we always run the UPDATE. This is probably overkill for the topological part, as toTopoGeom will be called again for every feature's geometry. In turn, the second call for an existing polygon may result in more edge splitting, as per https://trac.osgeo.org/postgis/ticket/2175

**Comment by strk** [comment]
Postponing this PR to after #25 is completed (implementation of #25 is currently already included in this PR but we want to split it out)

**Pull request merged**
